### ISSUE TITLE
Regarding frontend customization

### ISSUE THREAD

**Issue by Ashurali** [RTippin/messenger-ui#10]
If I want to change or customize the front end to fit my overall website design, how would I go about doing that?
Please advise and thank you for your time.

**Comment by RTippin** [comment]
@Ashurali 

 1. Fork this repo.
 2. Run `npm install && composer install`
 3. Edit the JS templates/managers to your liking. https://github.com/RTippin/messenger-ui/tree/master/resources/js
 4. Run `npm run prod` to recompile your assets into the app.js/app.css. Commit and push to your fork.
 5. Install your forked version into your laravel app, publish the messenger-ui assets, overwriting the previous with your newly updated assets.
