### ISSUE TITLE
Retiring MomentJS

### ISSUE THREAD

**Issue by d-damien** [RTippin/messenger-ui#2]
Hello,

As per their front page, [MomentJS](https://momentjs.com) is more or less retired. It also increases considerably the size of the bundle.

I personally favor [DayJS](https://day.js.org), which is more reliable (immutability) and lighter (modular).

Regards

**Comment by RTippin** [comment]
Thanks for the heads up, I will look into that and see if I can swap that out later today.

**Comment by RTippin** [comment]
@d-damien I have published `v2.0.0` which removes moment for dayjs, as well as switching socketio/laravel-echo-server out for pusher/laravel-websockets. Thanks for the suggestions :)
