### ISSUE TITLE
Group Voice Call 

### ISSUE THREAD

**Issue by aeq-dev** [RTippin/messenger-ui#4]
Hello,
Thank you for this great package,
Please, how could I use it to make a group voice call (same as twitter space) using a janus server ?
Thanks

**Comment by RTippin** [comment]
Well my janus-client package only has the video room plugin implemented, though you can use the core Janus facade to use the underlying communications methods. You could also make your own plugin for their audio bridge plugin by extending my [BasePlugin](https://github.com/RTippin/janus-client/blob/master/src/Plugins/BasePlugin.php) as I do not plan to implement that myself right now.

It is possible to start a video room but configure it with audio only, so no one would be publishing their video source. I suggest reading through their documentation for the audio bridge and the video room plugins:

> https://janus.conf.meetecho.com/docs/audiobridge.html
> https://janus.conf.meetecho.com/docs/videoroom.html

As for my messenger and UI packages, I have no plan to change any functionality that currently exists, though you can change to your own custom [VideoDriver](https://github.com/RTippin/messenger/blob/1.x/docs/Calling.md#implementing-our-videodriver) so when a call is created, perhaps you change the parameters sent to janus.

**Comment by aeq-dev** [comment]
Thank you so much @RTippin
