### ISSUE TITLE
How to search in all users? And add participants in a group?

### ISSUE THREAD

**Issue by arifhossen-dev** [RTippin/messenger-ui#6]
# 1. How can a user search all users (including new fresh users) for conversations?
# In the users table
![](https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/f1e66ca6-1ba6-42f8-a5df-3dee759a273e.gif?ClientID=vimeo-core-prod&Date=1647025544&Signature=907e1d3ba3ad1792b7d6ceb45fbbe77907f08cb5)

# Getting only logged in user
## I want to get search results from all new users. Logged in or not.
![](https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/c01476d2-ef81-4fbe-bf3e-8764970259b9.gif?ClientID=vimeo-core-prod&Date=1647025588&Signature=afa6d23901687b802d2722d122c3b3597ccc923c)

# in user model 
## Implements
```php
class User extends Authenticatable implements MessengerProvider
```
## Using traite
```php
use Messageable;
```
## Setting method
```php
   public static function getProviderSettings(): array
    {
        return [
            'alias' => 'user',
            'searchable' => true,
            'friendable' => true,
            'devices' => true,
            'default_avatar' => public_path('vendor/messenger/images/users.png'),
            'cant_message_first' => [],
            'cant_search' => [],
            'cant_friend' => [],
        ];
    }
```

## Searchable method
```php
   public static function getProviderSearchableBuilder(
        Builder $query,
        string $search,
        array $searchItems
    ) {
        $query->where(function (Builder $query) use ($searchItems) {
            foreach ($searchItems as $item) {
                $query->orWhere('name', 'LIKE', "%{$item}%");
            }
        })->orWhere('email', '=', $search);
    }
```

# 2. How can users add participants in a group without being friends?
I am using `BIGINT` id in the users table

**Comment by RTippin** [comment]
Please do not cross-post issues. This issue was handled:
> https://github.com/RTippin/messenger/issues/40
