### ISSUE TITLE
How to hide actions btns?

### ISSUE THREAD

**Issue by baskarcm** [RTippin/messenger-ui#7]
How to hide thread dropdown menu, knocks and close btns? and also message msg reaction, forward, etc.,?
![Screenshot (114)](https://user-images.githubusercontent.com/78421974/219374633-0109f0ca-b90c-4328-9bbe-977cbb256421.jpg)

**Comment by RTippin** [comment]
1. Fork this repo.
 2. Run `npm install && composer install`
 3. Edit the JS templates to your liking.
 4. Run `npm run prod` to recompile your assets into the app.js/app.css. Commit and push to your fork.
 5. Install your forked version into your laravel app, publish the messenger-ui assets, overwriting the previous with your newly updated assets.

Message options:
https://github.com/RTippin/messenger-ui/blob/master/resources/js/templates/ThreadTemplates.js#L396-L434

Group thread header:
https://github.com/RTippin/messenger-ui/blob/master/resources/js/templates/ThreadTemplates.js#L670-L703

Private thread header:
https://github.com/RTippin/messenger-ui/blob/master/resources/js/templates/ThreadTemplates.js#L741-L768

**Comment by baskarcm** [comment]
Thanks for your valuable reply.
